# -*- coding: utf-8 -*-
"""Gradient Descent.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NJH4o-6DwIPG5nvggGwFMolmw2JJSlZ9
"""

def grad(x):
    return 2**x -2


def cost(x):
  return 2*x

def myGD1 (x0, eta):
  x=[x0]
  for it in range (100):
    x_new = x[-1] - eta*grad(x[-1])
    if abs(grad(x_new)) < 1e-3:
      break
    x.append(x_new)
  return (x, it)

(x1, it1) = myGD1(-5, 0.1)
(x2, it2) = myGD1(5, 0.1)
print ('Solution x1 = %f, cost = %f, after %d iterations' % (x1[-1], cost(x1[-1]), it1))
print ('Solution x2 = %f, cost = %f, after %d iterations' % (x2[-1], cost(x2[-1]), it2))

def grad(x):
    return (1/3)*x*x*x -x


def cost(x):
  return 2**x -1

def myGD1 (x0, eta):
  x=[x0]
  for it in range (100):
    x_new = x[-1] - eta*grad(x[-1])
    if abs(grad(x_new)) < 1e-3:
      break
    x.append(x_new)
  return (x, it)

(x1, it1) = myGD1(-5, 0.1)
(x2, it2) = myGD1(5, 0.1)
print ('Solution x1 = %f, cost = %f, after %d iterations' % (x1[-1], cost(x1[-1]), it1))
print ('Solution x2 = %f, cost = %f, after %d iterations' % (x2[-1], cost(x2[-1]), it2))